CC = gcc
CFLAGS = -Wall -Wextra -Werror
CFILES =	ft_atoi.c
			ft_isalnum.c
			ft_isalpha.c
			ft_isascii.c
			ft_isdigit.c
			ft_isprint.c
			ft_strlen.c
			ft_strncmp.c
			ft_tolower.c
			ft_toupper.c

all:

